# Generated by Django 4.1.4 on 2023-01-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="About",),
        migrations.DeleteModel(name="Home",),
    ]
