# Generated by Django 4.1.4 on 2023-01-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_delete_about_delete_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="home_data",
            name="excel",
            field=models.FileField(default="None", upload_to="excel"),
        ),
        migrations.AlterField(
            model_name="home_data", name="html", field=models.TextField(default=""),
        ),
    ]
