# Generated by Django 4.1.4 on 2023-01-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_home_data_excel_alter_home_data_html"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("file", models.ImageField(upload_to="images")),
                ("html", models.TextField(default="")),
            ],
        ),
    ]
