# Generated by Django 4.1.4 on 2023-01-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home_data",
            name="excel",
            field=models.FileField(upload_to="excel"),
        ),
    ]
